# Generated by Django 4.0.4 on 2023-12-02 01:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAdmin',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('esProjectAdmin', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Admin',
                'verbose_name_plural': 'Project Admins',
            },
            bases=('tasks.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('esProjectMember', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
            },
            bases=('tasks.baseuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRegistratedMembers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('charge', models.CharField(max_length=64, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectMember', to='projects.projectmember')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Registrated Member',
                'verbose_name_plural': 'Project Registrated Members',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaTermino', models.DateTimeField(blank=True, null=True)),
                ('etiquetas', models.CharField(blank=True, max_length=100, null=True)),
                ('importancia', models.CharField(blank=True, max_length=100, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectregistratedmembers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.stage')),
            ],
            options={
                'verbose_name': 'Project Task',
                'verbose_name_plural': 'Project Tasks',
            },
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='projects.projectmember')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='projects.projectadmin')),
            ],
            options={
                'verbose_name': 'Project Invitation',
                'verbose_name_plural': 'Project Invitations',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProjectAdmin', to='projects.projectadmin'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='projects.ProjectRegistratedMembers', to='projects.projectmember'),
        ),
    ]
